version: '3'

services:
  vue:
    container_name: vue
    cpus: 2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules